// Generates complete CSS for index.css (CommonJS)
// Renamed to .cjs for ESM project compatibility
const fs = require("node:fs");

const p1 = [
"/* ============================================================ ",
"   ESTATEFLOW CRM - Design System & Styles                      ",
"   ============================================================ */",
"",
"/* ================================================================= ",
"   1. DESIGN TOKENS                                                  ",
"   ================================================================= */",
"",
":root {",
"  --color-primary:       #2563eb;",
"  --color-primary-dark:  #1d4ed8;",
"  --color-primary-light: #dbeafe;",
"  --color-primary-bg:    #eef4ff;",
"  --color-success:       #059669;",
"  --color-success-dark:  #047857;",
"  --color-success-bg:    #ecfdf5;",
"  --color-warning:       #d97706;",
"  --color-warning-dark:  #b45309;",
"  --color-warning-bg:    #fffbeb;",
"  --color-danger:        #dc2626;",
"  --color-danger-dark:   #b91c1c;",
"  --color-danger-bg:     #fef2f2;",
"  --color-text:          #101828;",
"  --color-text-secondary:#475569;",
"  --color-muted:         #94a3b8;",
"  --color-border:        #e2e8f0;",
"  --color-border-light:  #f0f2f5;",
"  --color-surface:       #ffffff;",
"  --color-bg:            #f8fafc;",
"  --color-bg-dark:       #f1f5f7;",
"  --text-xs:   0.75rem;",
"  --text-sm:   0.8125rem;",
"  --text-base: 0.875rem;",
"  --text-lg:   1rem;",
"  --text-xl:   1.25rem;",
"  --text-2xl:  1.5rem;",
"  --text-3xl:  1.875rem;",
"  --space-1:  0.25rem;",
"  --space-2:  0.5rem;",
"  --space-3:  0.75rem;",
"  --space-4:  1rem;",
"  --space-5:  1.25rem;",
"  --space-6:  1.5rem;",
"  --space-8:  2rem;",
"  --space-10: 2.5rem;",
"  --space-12: 3rem;",
"  --radius-sm:   6px;",
"  --radius-md:   8px;",
"  --radius-lg:   12px;",
"  --radius-xl:   16px;",
"  --radius-2xl:  20px;",
"  --radius-full: 9999px;",
"  --shadow-sm: 0 1px 3px rgba(0,0,0,0.04);",
"  --shadow-md: 0 4px 15px rgba(0,0,0,0.05);",
"  --shadow-lg: 0 8px 25px rgba(0,0,0,0.08);",
"  --shadow-xl: 0 20px 60px rgba(0,0,0,0.08);",
"  --transition-fast: 150ms ease;",
"  --transition-base: 200ms ease;",
"};"
].join("\n");

fs.writeFileSync("src/index.css", p1 + "\n", "utf8");
const p2 = [
"",
"/* ================================================================= ",
"   2. RESET & BASE                                                   ",
"   ================================================================= */",
"",
"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }",
"html { min-width: 320px; background: var(--color-bg); }",
"body { min-width: 320px; font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: var(--color-bg); color: var(--color-text); line-height: 1.5; -webkit-font-smoothing: antialiased; }",
"button, input, select, textarea { font: inherit; }",
"button { cursor: pointer; }",
"a { color: var(--color-primary); text-decoration: none; }",
"button, a, input, select, textarea { -webkit-tap-highlight-color: transparent; }",
"button:focus-visible, a:focus-visible, input:focus-visible, select:focus-visible, textarea:focus-visible { outline: 3px solid rgba(37, 99, 235, 0.28); outline-offset: 2px; }",
"",
"/* ================================================================= ",
"   3. LAYOUT                                                         ",
"   ================================================================= */",
"",
".crm-layout { min-height: 100vh; display: flex; background: var(--color-bg); }",
".crm-main { flex: 1; margin-left: 245px; min-width: 0; padding-bottom: var(--space-8); }",
"",
".sidebar { width: 245px; min-height: 100vh; background: var(--color-surface); border-right: 1px solid var(--color-border); display: flex; flex-direction: column; position: fixed; left: 0; top: 0; bottom: 0; z-index: 10; }",
".sidebar-brand { height: 80px; display: flex; align-items: center; gap: 11px; padding: 0 var(--space-6); border-bottom: 1px solid var(--color-border-light); }",
".sidebar-logo { width: 38px; height: 38px; display: flex; align-items: center; justify-content: center; background: var(--color-primary); color: white; border-radius: 10px; font-size: 19px; font-weight: 700; }",
".sidebar-brand h2 { font-size: 17px; }",
".sidebar-brand span { color: var(--color-muted); font-size: var(--text-xs); }",
".sidebar-nav { padding: var(--space-6) var(--space-3); display: flex; flex-direction: column; gap: 5px; }",
".sidebar-link { display: flex; align-items: center; gap: var(--space-3); padding: 11px 13px; border-radius: var(--radius-md); color: var(--color-text-secondary); text-decoration: none; font-size: var(--text-base); font-weight: 500; transition: background-color var(--transition-fast), color var(--transition-fast); }",
".sidebar-link:hover { background: var(--color-bg); color: var(--color-primary); }",
".sidebar-link.active { background: var(--color-primary-bg); color: var(--color-primary); font-weight: 600; }",
".sidebar-bottom { margin-top: auto; padding: var(--space-4); border-top: 1px solid var(--color-border-light); }",
".sidebar-user { display: flex; align-items: center; gap: var(--space-2); padding: var(--space-2); margin-bottom: var(--space-2); }",
".sidebar-avatar { width: 36px; height: 36px; display: flex; align-items: center; justify-content: center; border-radius: 50%; background: var(--color-primary-bg); color: var(--color-primary); font-weight: 700; }",
".sidebar-user div:last-child { display: flex; flex-direction: column; gap: 2px; }",
".sidebar-user strong { font-size: 13px; }",
".sidebar-user span { color: var(--color-muted); font-size: var(--text-xs); }",
".sidebar-logout { width: 100%; display: flex; align-items: center; gap: 9px; border: none; background: transparent; padding: var(--space-2); border-radius: var(--radius-md); color: var(--color-text-secondary); text-align: left; transition: background-color var(--transition-fast), color var(--transition-fast); }",
".sidebar-logout:hover { background: var(--color-danger-bg); color: var(--color-danger); }",
"",
".page-container { padding: var(--space-8); }",
".page-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: var(--space-6); }",
".page-header h1 { font-size: var(--text-2xl); margin-bottom: 5px; }",
".page-header p { color: var(--color-text-secondary); font-size: var(--text-base); }",
".page-header-actions { display: flex; align-items: center; gap: var(--space-2); }",
".section-header { display: flex; justify-content: space-between; align-items: center; margin: var(--space-8) 0 var(--space-4); }",
".section-header h2 { margin: 0; font-size: var(--text-xl); color: var(--color-text); }",
".section-header p { margin: 5px 0 0; color: var(--color-text-secondary); font-size: var(--text-base); }",
"",
".dashboard-page { padding: var(--space-8); }",
".dashboard-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: var(--space-6); }",
".dashboard-header h1 { font-size: var(--text-2xl); margin-bottom: 6px; }",
".dashboard-header p { color: var(--color-text-secondary); }",
".header-actions { display: flex; align-items: center; gap: var(--space-3); }",
".dashboard-grid { display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-6); margin-bottom: var(--space-6); }",
".dashboard-card { background: var(--color-surface); border: 1px solid var(--color-border); border-radius: var(--radius-lg); padding: var(--space-6); box-shadow: var(--shadow-sm); }",
].join("\n");

fs.appendFileSync("src/index.css", p2 + "\n", "utf8");